name: Estimate hours
on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install gitoxide
        run: yes | cargo-binstall gitoxide

      - name: Estimate hours
        run: echo $(ein tool estimate-hours) > .dev_hours

      - name: Add log file
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .dev_hours

      - name: Commit log file
        run: "git commit -m 'chore: Estimate potential development hours'"

      - name: Open pull request
        run: gh pr create >-
          --head
          --no-maintainer-edit
          --assignee ${{ github.actor }}
          --title "(${{ github.run_attempt }}) Estimate potential development hours"
          --body "Estimates the number of hours spent on developing this project based on its commit history."
