name: Estimate hours
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install gitoxide
        run: yes | cargo-binstall gitoxide

      - name: Estimate hours
        run: echo $(ein tool estimate-hours) > .dev_hours

      - name: Commit log file
        run: "git add .dev_hours && git commit -m 'chore: Estimate development hours'"

      - name: Open pull request
        run: gh pr create -Hf
